### ISSUE TITLE
About the speed of box convolution

### ISSUE THREAD

**Issue by dontLoveBugs** [shrubb/box-convolutions#13]
In the paper, you replace every second block in ENet with your proposed box conv block. But I find if not using cuda, box block have almost the same speed with the original block, but if using cuda, the box block is much slower than the original block. Is that right? And why?
The ENet original block is from [PyTorch-ENet](https://github.com/davidtvs/PyTorch-ENet). I define your proposed block is as following:
```
class BoxBlock(nn.Module):
    """
    The block architecture that is used to embed box convolution into Enet.
    """

    def __init__(self, channels, input_size=(512, 512), dropout_prob=0):
        super(BoxBlock, self).__init__()
        self.channels = channels

        self.conv1x1 = nn.Sequential(nn.Conv2d(self.channels, self.channels // 4, kernel_size=1, bias=False),
                                     nn.BatchNorm2d(self.channels // 4),
                                     nn.ReLU(inplace=True))

        w, h = input_size
        self.box_conv = nn.Sequential(BoxConv2d(in_planes=self.channels // 4,
                                                num_filters=4, max_input_h=h, max_input_w=w),
                                      nn.BatchNorm2d(self.channels),
                                      nn.Dropout2d(p=dropout_prob))

        self.relu = nn.ReLU(inplace=True)

    def forward(self, input):
        x = self.conv1x1(input)
        x = self.box_conv(x)
        x = x + input
        return self.relu(x)
```

I use the following test code. 

```
    cuda = False

    input = torch.randn(1, 128, 64, 64)
    if cuda:
        input = input.cuda()

    ori_block = RegularBottleneck(128, dilation=8, padding=8, dropout_prob=0.1, relu=True)
    box_block = BoxBlock(channels=128, input_size=(64, 64), dropout_prob=0.25)

    if cuda:
        ori_block = ori_block.cuda()
        box_block = box_block.cuda()

    end = time.time()
    y = ori_block(input)
    end = time.time() - end

    if cuda:
        print('if cuda, ori block run time = ', end)
    else:
        print('if no cuda, ori block run time = ', end)

    end = time.time()
    y = box_block(input)
    end = time.time() - end

    if cuda:
        print('if cuda, box block run time = ', end)
    else:
        print('if no cuda, box block run time = ', end)
```

The test result is:
![image](https://user-images.githubusercontent.com/17598076/53415379-13570780-3a0c-11e9-9575-a2be55a9670c.png)

![image](https://user-images.githubusercontent.com/17598076/53415352-00443780-3a0c-11e9-9fd9-c3b1a2388c5a.png)

**Comment by shrubb** [comment]
Let me explicate:

* Your benchmarking script is wrong. When you time CUDA code, you should
  * "warm up" to pre-initialize context,
  * synchronize the GPU before and after (because CUDA kernels are asynchronous),
  * preferably do the operation multiple times.
* [Here](https://github.com/shrubb/box-convolutions/blob/master/examples/convnet-runtime-benchmark.py) is the (translated) script used in the paper.
* Here are the exact models used and benchmarked in the paper: [ENet](https://github.com/shrubb/box-convolutions/blob/master/examples/ENet.py), [ERFNet](https://github.com/shrubb/box-convolutions/blob/master/examples/ERFNet.py).
* The paper doesn't claim that our block is faster. The CNN overall is.

**Comment by dontLoveBugs** [comment]
Thanks
