### ISSUE TITLE
YOLO architecture

### ISSUE THREAD

**Issue by Flock1** [shrubb/box-convolutions#16]
Hi,

I want to know if there's some way I can create an architecture that'll work with YOLO. I've read a lot of implementations with pytorch but I don't know how should I modify the `cfg` file so that I can add `box convolution` layer.

Let me know.

**Comment by shrubb** [comment]
Hi, I personally have absolutely no clue what is YOLO. Maybe someone else experienced in object detection will join comments.

**Comment by Flock1** [comment]
Okay, thanks.

**Comment by Flock1** [comment]
@shrubb, just so I got this right, your box convolution layer is a sublayer for the convolution layer?

Also, how do the parameters within the box convolution layer help with improving the computation efficiency? Can you give me a small summary there?

**Comment by shrubb** [comment]
I'm not sure what you mean by "sublayer for another layer". Box convolution is a separate standalone layer, you use it wherever it feels right, no restrictions really. It's just a different operation with its own usage cases. However, I often say that our layer IS a convolution (which is true) because then it's easier to explain the concept.

As usually happens in neural nets, the number of parameters has little to do with computational efficiency. Small number of parameters is a lucky side effect due to a very simple kernel used. Rather, box convolution is fast to compute because there is a special fast algorithm devised specifically for box kernels (google "integral images"), while conventional `nn.Conv2d()` has to use a slower general pixel-by-pixel algorithm.

**Comment by Flock1** [comment]
@shrubb I was referring to `x = self.conv1_1x1(self.conv1(x))` in the mnist code that was given. So I am guessing that the convolution layer is required to use the box convolution.

**Comment by shrubb** [comment]
Well, this isn't an absolute requirement. For example, instead of using 1x1 convolution, you could just somehow reduce all channels, i.e. take average/sum/product. I recommend 1x1 convolutions simply because box convolution only operates depthwise (channel by channel), while I usually want information to be spread across channels. "Depthwise separable convolutions" advocate this idea too, for same reason.

**Comment by Flock1** [comment]
Hmm. Okay. Just one more question. How does this convolution as well as box kernel operations (both of them at the same time) help reduce the processign time?

**Comment by shrubb** [comment]
Several factors here:

1. Most processing time in CNNs is spent on spatial operations. Box convolution itself involves less operations than most other common parametric methods of aggregating features over spatial regions, e.g. 3x3 convolution and even depthwise 3x3 convolution).
2. 1x1 convolution, which is often coupled with `BoxConv2d`, is computationally very cheap.
3. 3x3 convolutions only fuse information from a small surrounding area, that's why if you want your ConvNet to consider information from the whole image, you often need to make it very deep. Box convolution can average features over as large areas as you want, so with it the network is enabled to be shallower and thus faster.

**Comment by Flock1** [comment]
Hmm, Okay. Let me see if, in some way, I can implement your idea in to YOLO and probably improve the time taken. Thanks
